=== NonlinearFruit/Creeds.json/spec/metadata/Resources.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Android": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "Id": {
            "type": "string"
          },
          "Url": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          }
        },
        "required": [
          "Title",
          "Id",
          "Url",
          "Description"
        ]
      }
    },
    "Books": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "Author": {
            "type": "string"
          },
          "PublishYear": {
            "type": "integer"
          },
          "Url": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          }
        },
        "required": [
          "Title",
          "Author",
          "PublishYear",
          "Url",
          "Description"
        ]
      }
    },
    "Data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "UserRepo": {
            "type": "string"
          },
          "Url": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          }
        },
        "required": [
          "Title",
          "UserRepo",
          "Url",
          "Description"
        ]
      }
    },
    "Websites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "Url": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          }
        },
        "required": [
          "Title",
          "Url",
          "Description"
        ]
      }
    },
    "iOS": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Title": {
            "type": "string"
          },
          "Url": {
            "type": "string"
          },
          "Description": {
            "type": "string"
          }
        },
        "required": [
          "Title",
          "Url",
          "Description"
        ]
      }
    }
  },
  "required": [
    "Android",
    "Books",
    "Data",
    "Websites",
    "iOS"
  ]
}

=== NonlinearFruit/Creeds.json/metadata/resources.json
{
  "Android": [ 
    {
      "Title": "Creeds",
      "Id": "com.nonlinearfruit.creeds",
      "Url": "https://play.google.com/store/apps/details?id=com.nonlinearfruit.creeds",
      "Description": "Read, search, copy classic creeds"
    },
    {
      "Title": "Creeds and Confessions",
      "Id": "nz.co.conglomo.confessions",
      "Url": "https://play.google.com/store/apps/details?id=nz.co.conglomo.confessions",
      "Description": "Creeds and Confessions Mobile App"
    }
  ],
  "Books": [ 
    {
      "Title": "Creeds of Christendom (Vol 1-3)",
      "Author": "Philip Schaff",
      "PublishYear": 1876,
      "Url": "https://www.ccel.org/ccel/schaff/creeds1",
      "Description": "Through Creeds of Christendom, Schaff aims to bring understanding to those who adhere to different creeds. He wisely reminds us that despite varying Christian denominations, Christ always remains at the center of the creeds."
    },
    {
      "Title": "Reformed Confessions of the 16th and 17th Centuries (Vol 1-4)",
      "Author": "James T. Dennison Jr",
      "PublishYear": 2008,
      "Url": "https://www.heritagebooks.org/products/reformed-confessions-of-the-16th-and-17th-centuries-in-english-translation-volume-1-1523-1552-dennison-ed.html",
      "Description": "This four volume set compiles numerous Reformed confessions of the sixteenth and seventeenth centuries translated into English. For many of these texts, this is their debut in the Anglo-Saxon vernacular."
    }
  ],
  "Data": [ 
    {
      "Title": "Creeds.json",
      "UserRepo": "NonlinearFruit/Creeds.json",
      "Url": "https://github.com/NonlinearFruit/Creeds.json",
      "Description": "You're looking at it!"
    },
    {
      "Title": "Standards Bot",
      "UserRepo": "Nokeo08/standardsbot",
      "Url": "https://github.com/Nokeo08/standardsbot",
      "Description": "A reddit bot that is triggered by reddit comments made in /r/Reformed that references various christian confessions and catechisms."
    },
    {
      "Title": "Reformed Standards",
      "UserRepo": "reformed-standards/compendium",
      "Url": "https://github.com/reformed-standards/compendium",
      "Description": "The compendium is a collection of reformed documents, such as confessions and catechisms."
    }
  ],
  "Websites": [ 
    {
      "Title": "Awesome Bible Developer Resources",
      "Url": "https://github.com/biblenerd/awesome-bible-developer-resources",
      "Description": "A curated list of awesome resources for developers (and other nerds) working with biblical texts and related tools."
    },
    {
      "Title": "Catechesis",
      "Url": "https://www.catechesis.app",
      "Description": "An open-source app designed to help you catechize yourself, your family, and your church - by engaging with catechisms that have stood the test of time throughout the church age."
    },
    {
      "Title": "Creeds",
      "Url": "https://nonlinearfruit.github.io/Creeds-Blazor/",
      "Description": "Read, search, copy classic creeds"
    },
    {
      "Title": "Reformed Standards",
      "Url": "https://reformedstandards.com",
      "Description": "All the reformed documents in one tidy package"
    },
    {
      "Title": "Creeds and Confessions",
      "Url": "https://confessions.azurewebsites.net",
      "Description": ""
    },
    {
      "Title": "Westminster Assembly Project",
      "Url": "https://westminsterassembly.org",
      "Description": "The Westminster Assembly Project exists to make the writings of the Westminster Assembly and its members available to scholars and to the general public."
    },
    {
      "Title": "Relight",
      "Url": "https://relight.app",
      "Description": "Relight dreams of one day becoming a fully-featured app for studying the Bible and theology from a reformed perspective."
    }
  ],
  "iOS": [ 
    {
      "Title": "Christian Creeds & Confessions",
      "Url": "https://apps.apple.com/us/app/christian-creeds-confessions/id359513722#?platform=iphone",
      "Description": "This application provides a searchable library of the most universally used Christian creeds, confessions and catechisms of the Continental Reformed and English Presbyterian churches."
    }
  ]
}
